services:
  fastapi:
    build: ./Api-Gestor-de-Tareas
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: always

  angular:
    build: ./fronted-Gestor-de-Tareas
    container_name: angular_app
    ports:
      - "80:80"
    restart: always

  db:
    image: mysql:8.0
    container_name: fastapi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"